language: java
install: true
script: mvn -Pdeploy-to-imagej deploy --settings settings.xml
env:
  matrix:
    secure: FVxqh3AbSIoS2iADCcfydpsYyE7ZhDXGFSo93ZHJ93VaZMIGYJCuxC5SWhm3GSL7h/6M/LIpEe/T+FMIr5qSBNfqQ/CmFkVPogaTHuY1tHg6r6u0ovGBxOBroDKTkjxmKIGSUB4rtkXRYv3hYoU26xd0VtUthIgpFq8gZ7Nfre4=
